config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :barangays
  resources :cities
  resources :provinces
  resources :regions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/barangay.rb
class Barangay < ApplicationRecord
end

app/controllers/barangays_controller.rb
class BarangaysController < ApplicationController
  before_action :set_barangay, only: %i[ show edit update destroy ]

  # GET /barangays or /barangays.json
  def index
    @barangays = Barangay.all
  end

  # GET /barangays/1 or /barangays/1.json
  def show
  end

  # GET /barangays/new
  def new
    @barangay = Barangay.new
  end

  # GET /barangays/1/edit
  def edit
  end

  # POST /barangays or /barangays.json
  def create
    @barangay = Barangay.new(barangay_params)

    respond_to do |format|
      if @barangay.save
        format.html { redirect_to @barangay, notice: "Barangay was successfully created." }
        format.json { render :show, status: :created, location: @barangay }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @barangay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barangays/1 or /barangays/1.json
  def update
    respond_to do |format|
      if @barangay.update(barangay_params)
        format.html { redirect_to @barangay, notice: "Barangay was successfully updated." }
        format.json { render :show, status: :ok, location: @barangay }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @barangay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barangays/1 or /barangays/1.json
  def destroy
    @barangay.destroy
    respond_to do |format|
      format.html { redirect_to barangays_url, notice: "Barangay was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barangay
      @barangay = Barangay.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def barangay_params
      params.require(:barangay).permit(:list, :populations)
    end
end

app/helpers/barangays_helper.rb
module BarangaysHelper
end

app/views/barangays/_form.html.erb
<%= form_with(model: barangay, local: true) do |form| %>
  <% if barangay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(barangay.errors.count, "error") %> prohibited this barangay from being saved:</h2>

      <ul>
      <% barangay.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :list %>
    <%= form.text_field :list %>
  </div>

  <div class="field">
    <%= form.label :populations %>
    <%= form.text_area :populations %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/barangays/edit.html.erb
<h1>Editing Barangay</h1>

<%= render 'form', barangay: @barangay %>

<%= link_to 'Show', @barangay %> |
<%= link_to 'Back', barangays_path %>

app/views/barangays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Barangays</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>Populations</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @barangays.each do |barangay| %>
      <tr>
        <td><%= barangay.list %></td>
        <td><%= barangay.populations %></td>
        <td><%= link_to 'Show', barangay %></td>
        <td><%= link_to 'Edit', edit_barangay_path(barangay) %></td>
        <td><%= link_to 'Destroy', barangay, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barangay', new_barangay_path %>

app/views/barangays/new.html.erb
<h1>New Barangay</h1>

<%= render 'form', barangay: @barangay %>

<%= link_to 'Back', barangays_path %>

app/views/barangays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @barangay.list %>
</p>

<p>
  <strong>Populations:</strong>
  <%= @barangay.populations %>
</p>

<%= link_to 'Edit', edit_barangay_path(@barangay) %> |
<%= link_to 'Back', barangays_path %>