config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :barangays
  resources :cities
  resources :provinces
  resources :regions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/province.rb
class Province < ApplicationRecord
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: %i[ show edit update destroy ]

  # GET /provinces or /provinces.json
  def index
    @provinces = Province.all
  end

  # GET /provinces/1 or /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces or /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: "Province was successfully created." }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1 or /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: "Province was successfully updated." }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1 or /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url, notice: "Province was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def province_params
      params.require(:province).permit(:list, :description)
    end
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/provinces/_form.html.erb
<%= form_with(model: province, local: true) do |form| %>
  <% if province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% province.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :list %>
    <%= form.text_field :list %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/provinces/edit.html.erb
<h1>Editing Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Provinces</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.list %></td>
        <td><%= province.description %></td>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Province', new_province_path %>

app/views/provinces/new.html.erb
<h1>New Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Back', provinces_path %>

app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @province.list %>
</p>

<p>
  <strong>Description:</strong>
  <%= @province.description %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>