config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :barangays
  resources :cities
  resources :provinces
  resources :regions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/region.rb
class Region < ApplicationRecord
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: %i[ show edit update destroy ]

  # GET /regions or /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1 or /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions or /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: "Region was successfully created." }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1 or /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: "Region was successfully updated." }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1 or /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: "Region was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def region_params
      params.require(:region).permit(:region_name, :description)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_with(model: region, local: true) do |form| %>
  <% if region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :region_name %>
    <%= form.text_field :region_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Regions</h1>

<table>
  <thead>
    <tr>
      <th>Region name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.region_name %></td>
        <td><%= region.description %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Region', new_region_path %>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Region name:</strong>
  <%= @region.region_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @region.description %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>